name: Hourly Backup

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client
    
    - name: Create restorable backup snapshot
      env:
        PGHOST: db.wnutwvmxpbtduhfthcah.supabase.co
        PGPORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Creating restorable backup snapshot..."
        psql -v ON_ERROR_STOP=1 -c "SELECT public.snapshot_entire_backups_table_simple();"
    
    - name: Update backups timestamp
      env:
        PGHOST: db.wnutwvmxpbtduhfthcah.supabase.co
        PGPORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Updating backups timestamp..."
        psql -v ON_ERROR_STOP=1 -c "UPDATE public.backups SET updated_at = NOW();"
    
    - name: Cleanup old backups
      env:
        PGHOST: db.wnutwvmxpbtduhfthcah.supabase.co
        PGPORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      run: |
        echo "Cleaning up old backups..."
        psql -v ON_ERROR_STOP=1 -c "SELECT public.prune_backup_history(168, 7);"
    
    - name: Success
      run: |
        echo "Hourly backup completed successfully!"
        echo "- Created restorable snapshot"
        echo "- Updated timer"
        echo "- Cleaned up old backups"
