name: Hourly Backup

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Hourly Backup
      run: |
        curl -X POST "https://${{ secrets.SUPABASE_URL }}/functions/v1/hourly-backup" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
      
    - name: Check Response
      run: |
        echo "Backup triggered successfully"
